### PR TITLE
Add OTB100 seqs

### PR DESCRIPTION
**Pull request by HakaseH**

### CODE REVIEW

**Comment by foolwood** [comment]
I upload the full configSeqs.m(OTB100  OTB50 CVPR2013) in OTB100.zip.
Do you have the **initOmit** file for the OTB100. That's what we should share. 
Thanks for your  pull request. We can write a technical tutorial in the future.

**Comment by HakaseH** [comment]
Thank you for sharing. 
I don't have other **initOmit** files. Do you have the table of all initOmit frames? I don't find any information on the benchmark website.

**Comment by bertinetto** [comment]
Actually...
In the PAMI15 paper of OTB they explicitly say that they haven't use
initOmit.
See Section 6:

> *[...] Note that in this benchmark, we annotate each target object in
> every frame even when it is fully occluded.*

**Comment by foolwood** [comment]
@bertinetto 
A little embarrassed. w(ﾟДﾟ)w

**Pull request closed without merging**
